---
- name: Создание системных групп
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  loop: "{{ system_groups }}"
  tags:
    - groups
    - add_groups

- name: Проверка существования группы kamailio
  ansible.builtin.group:
    name: kamailio
    state: present
  tags:
    - groups
    - kamailio
